apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-root-working
  namespace:
  labels:
    run: nginx
spec:
  containers:
  - image: bitnami/nginx:latest
    name: nginx
    securityContext:
      runAsNonRoot: true
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    - name: https
      containerPort: 8443
      protocol: TCP