apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace:
  labels:
data:
  nginx.conf: |
    server {
        listen       80;
        server_name facebook.com;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm home.html;
        }
    }
