apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
    mykey: myvalue
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 1
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 20
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 1
