apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace:
  labels:
    run: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "1"
    ports:
    - name: mysql
      protocol: TCP
      containerPort: 3306
    livenessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 10
      timeoutSeconds: 10
      periodSeconds: 5
      failureThreshold: 1
    readinessProbe:
      exec:
        # Check we can execute queries over TCP
        command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
      initialDelaySeconds: 30
      timeoutSeconds: 20
      periodSeconds: 60
      failureThreshold: 3
